services:
  liferay:
    image: liferay/dxp:7.4.13-u45
    container_name: liferay-dxp
    restart: always
    ports:
      - "8080:8080"
    environment:
      - LIFERAY_JVM_OPTS=-Xms2g -Xmx2g
    volumes:
      - ./deploy:/opt/liferay/deploy
      - ./configs/portal-ext.properties:/opt/liferay/portal-ext.properties