name: Liferay CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 🎯 Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 🔨 Build Liferay Project
        run: ./gradlew build

      - name: ✅ Run Tests
        run: ./gradlew test

  sonarqube:
    name: SonarQube Code Analysis
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔍 SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"

  docker:
    name: Build & Push Docker Image
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔑 Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏗️ Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/liferay-car-service:latest .

      - name: 🚀 Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/liferay-car-service:latest

  deploy:
    name: Deploy to Kubernetes
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: 🚀 Deploy to Kubernetes
        run: |
          kubectl set image deployment/liferay-car-service liferay-car-service=${{ secrets.DOCKERHUB_USERNAME }}/liferay-car-service:latest
          kubectl rollout status deployment/liferay-car-service
