version: '3.8'
services:
  liferay:
    image: liferay/dxp:7.4.13-u92
    container_name: liferay-dxp
    restart: always
    ports:
      - "8080:8080"
    environment:
      - LIFERAY_JVM_OPTS=-Xms4g -Xmx4g
      - LIFERAY_JDBC_DEFAULT_URL=jdbc:mysql://mysql:3306/lportal
      - LIFERAY_JDBC_DEFAULT_USERNAME=liferay
      - LIFERAY_JDBC_DEFAULT_PASSWORD=liferay
    volumes:
      - ./deploy:/opt/liferay/deploy
      - ./configs/portal-ext.properties:/opt/liferay/portal-ext.properties
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: liferay-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lportal
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
